Models/ErrorViewModel.cs
using System;

namespace Lab3_test3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/NameLoopFormModel.cs
using System.ComponentModel.DataAnnotations;
namespace Lab3_test3.Models
{
    public class NameLoopFormModel
    {
        [Display(Name = "Imię")]
        [Required]
        public string Name { get; set; }
        [Display(Name = "Ilość pętli")]
        public int LoopAmount { get; set; }
    }
}

Controllers/HomeController.cs
using Lab3_test3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Lab3_test3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index(int id)
        {
            ViewData["param1"] = id;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/NameLoopController.cs
using Microsoft.AspNetCore.Mvc;
using Lab3_test3.Models;

namespace Lab3_test3.Controllers
{
    public class NameLoopController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Loop(NameLoopFormModel model)
        {
            if (ModelState.IsValid)
            {
                return View("Loop", model);
            }
            return View(model);
        }
    }
}

Views/Home/Index.cshtml
@model Lab3_test3.Models.NameLoopFormModel

@{ ViewData["Title"] = "Imię-Pętla"; }

<h1 class="display-4">@ViewData["Title"]</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-controller="NameLoop" asp-action="Loop" method="post">

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoopAmount" class="control-label"></label>
                <select asp-for="LoopAmount">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                <span asp-validation-for="LoopAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapętlij Imię" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


Views/NameLoop/Loop.cshtml
@model Lab3_test3.Models.NameLoopFormModel

@{
    ViewData["Title"] = "Pętla-Imienia";
}

@for (int i = 0; i < Model.LoopAmount; i++)
{
    <p>@Html.DisplayFor(model => model.Name)</p>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab3_test3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Imię-Petla</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Imię-Petla
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>